### ISSUE TITLE
`mdformat 0.7.19` support

### ISSUE THREAD

**Issue by jorenham** [csala/mdformat-pyproject#2]
Apparently `mdformat 0.7.19` (silently) introduced a breaking change ([release notes](https://mdformat.readthedocs.io/en/stable/users/changelog.html#id1)), which causes `mdformat-pyproject` to crash on invocation.

To illustrate, in the CI of [`scipy-stubs`](https://github.com/jorenham/scipy-stubs) the following command is run:

```
mdformat CODE_OF_CONDUCT.md CONTRIBUTING.md README.md SECURITY.md tests/README.md --check
```

But since upgrading to `mdformat==0.7.19`, it crashes:

```
Traceback (most recent call last):
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/bin/mdformat", line 8, in <module>
    sys.exit(run())
             ~~~^^
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.[13](https://github.com/jorenham/scipy-stubs/actions/runs/11915079805/job/33204492222?pr=183#step:7:14)/site-packages/mdformat/__main__.py", line 8, in run
    exit_code = mdformat._cli.run(sys.argv[1:])
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mdformat/_cli.py", line 125, in run
    formatted_str = mdformat.text(
        original_str,
    ...<6 lines>...
        _filename=path_str,
    )
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mdformat/_api.py", line 25, in text
    mdit = build_mdit(
        MDRenderer,
    ...<2 lines>...
        codeformatters=codeformatters,
    )
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mdformat/_util.py", line 39, in build_mdit
    plugin.update_mdit(mdit)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mdformat_pyproject/plugin.py", line 87, in update_mdit
    cli_opts = _reload_cli_opts()
  File "/home/runner/work/scipy-stubs/scipy-stubs/.venv/lib/python3.13/site-packages/mdformat_pyproject/plugin.py", line 71, in _reload_cli_opts
    arg_parser = mdformat._cli.make_arg_parser(enabled_parserplugins, enabled_codeformatters)
TypeError: make_arg_parser() missing 1 required positional argument: 'parser_extensions'
```

**Comment by csala** [comment]
Thanks for reporting this @jorenham

To be completely fair, the change was not silently introduced. I [was warned](https://github.com/executablebooks/mdformat/issues/378#issuecomment-2431385190), but when I reviewed the code the change did not look menacing, and I did not manage to make the time to fully dive into it.

Seeing that it does indeed provoke problems, I'll prioritize this and try to release a fix ASAP

**Comment by antazoey** [comment]
We are hitting this too, let me know if we can help.

**Comment by csala** [comment]
It turns out that the problem is actually related to something else, not [the PR about the cli arguments groups](https://github.com/executablebooks/mdformat/pull/461), and this is why it went in undetected.

The origin is [this change](https://github.com/executablebooks/mdformat/commit/8c573e4913ebb10a0bd30ae95b3620bd846856d7#diff-c02f6d0a0e71853913e80cc18ed2585c04982a48a285d2b5e9d907154c7313e8R155) in the `make_arg_parser` signature.

I've already fixed it and I'm now testing whether all the plugin options are being properly parsed.

**Comment by csala** [comment]
[v0.0.2](https://github.com/csala/mdformat-pyproject/releases/tag/v0.0.2) has been released, which fixes this issue.

**Comment by antazoey** [comment]
I have confirmed it fixes the issue in our projects

**Comment by jorenham** [comment]
Thanks @csala :)
